version: '3.7'

services:
  gui:
    image: moreillon/chartmuseum-gui:latest
    environment:
      PUBLIC_CHARTMUSEUM_URL: http://chartmuseum:8080
    ports:
      - 3000:3000

  chartmuseum:
    image: chartmuseum/chartmuseum:latest
    ports:
      - 8080:8080
    volumes:
      - ./charts:/charts
    environment:
      PORT: 8080
      DEBUG: 1
      STORAGE: local
      STORAGE_LOCAL_ROOTDIR: /charts
